global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'translation-api'
    static_configs:
      # assumes service not scaled beyond one instance
      # for multiple instances, manually switch to:
      # - targets: ['app:8000', 'app2:8000', 'app3:8000', ...]
      - targets: ['app:8000']
    metrics_path: '/metrics'